services:
  ros2:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ros2_humble

    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1

    working_dir: /workspace
    volumes:
      - ../workspace:/workspace
      - /dev/ttyUSB0:/dev/ttyUSB0
      - ./entrypoint_ros2.sh:/entrypoint_ros2.sh

    environment:
      - ROBOT_ID=${ROBOT_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    entrypoint: ["bash", "/entrypoint_ros2.sh"]

    privileged: true

    tty: true
    stdin_open: true
    command: bash
    restart: unless-stopped

  lidar:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    image: ros2_humble

    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1

    working_dir: /workspace
    volumes:
      - ../workspace:/workspace
      - /dev/ttyACM0:/dev/ttyACM0
      - ./entrypoint_lidar.sh:/entrypoint_lidar.sh

    environment:
      - ROBOT_ID=${ROBOT_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    entrypoint: ["bash", "/entrypoint_lidar.sh"]

    privileged: true

    tty: true
    stdin_open: true
    command: bash
    restart: unless-stopped
